import React, { useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
    Loader2, Download, Share2, Plus, Sparkles, Wand2, Layers,
    Presentation, Copy, Check, MessageCircle, Share
} from "lucide-react";
import pptxgen from "pptxgenjs";
import { useToast } from "@/components/ui/use-toast";
import { motion, AnimatePresence } from "framer-motion";

import api from "@/api/client";
import { toast } from "sonner";

export function PPTGeneratorTab() {
    const { toast: uiToast } = useToast();
    const [topic, setTopic] = useState('');
    const [grade, setGrade] = useState('');
    const [numSlides, setNumSlides] = useState('5');
    const [curriculum, setCurriculum] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedPPT, setGeneratedPPT] = useState<any>(null);
    const hasAutoGenerated = useRef(false);
    const [generationProgress, setGenerationProgress] = useState(0);

    const handleGenerate = async () => {
        if (!topic || !grade || !curriculum) {
            toast.error("Missing Information", {
                description: "Please fill in all required fields to generate the presentation."
            });
            return;
        }

        setIsGenerating(true);
        setGeneratedPPT(null);
        setGenerationProgress(0);

        // Progress simulation for UI feel
        const progressInterval = setInterval(() => {
            setGenerationProgress(prev => {
                if (prev >= 90) {
                    clearInterval(progressInterval);
                    return 90;
                }
                return prev + Math.random() * 10;
            });
        }, 800);

        try {
            const response = await api.post('/lessons/generate-ppt', {
                topic,
                grade,
                curriculum,
                slides: numSlides
            });

            const aiSlides = response.data;

            // Map AI slides to presentation format
            const formattedSlides = aiSlides.map((s: any, idx: number) => {
                let layout = "timeline_process";
                const type = (s.layout_type || '').toLowerCase();

                if (type === 'title') layout = "organic_title";
                else if (type === 'summary' || idx === aiSlides.length - 1) layout = "thank_you";
                else if (type === 'process') layout = "process_steps";
                else if (type === 'comparison') layout = "comparison_view";
                else if (type === 'intro') layout = "timeline_process";
                else layout = idx % 2 === 0 ? "timeline_process" : "centered_visual";

                // Map theme colors
                const themes = ['blue', 'orange', 'purple', 'emerald', 'rose'];
                const theme = themes[idx % themes.length];

                return {
                    ...s,
                    subtitle_1: s.subtitle || `GRADE ${grade} • ${curriculum.toUpperCase()}`,
                    subtitle_2: s.activity || "Presented by Co-Teacher AI",
                    layout,
                    theme,
                    image: s.image_url || `https://source.unsplash.com/featured/1600x900?${encodeURIComponent(s.image_keyword || topic)}`,
                    fullImage: s.image_url || `https://source.unsplash.com/featured/1600x900?${encodeURIComponent(s.image_keyword || topic)}`,
                    tag: type.toUpperCase() || "CONTENT"
                };
            });

            setGeneratedPPT({
                title: `${topic} (${curriculum.toUpperCase()} - Grade ${grade})`,
                slides: formattedSlides
            });

            clearInterval(progressInterval);
            setGenerationProgress(100);
            toast.success("Success", {
                description: "Your presentation has been generated."
            });
        } catch (error) {
            console.error("PPT Generation Error:", error);
            toast.error("Generation Failed", {
                description: "There was an error generating your presentation. Please try again."
            });
        } finally {
            setIsGenerating(false);
        }
    };

    useEffect(() => {
        const params = new URLSearchParams(window.location.search);
        const urlTopic = params.get('topic');
        const urlGrade = params.get('grade');
        const urlCurriculum = params.get('curriculum');
        const auto = params.get('autoGenerate');

        if (urlTopic) setTopic(urlTopic);
        if (urlGrade) setGrade(urlGrade);
        if (urlCurriculum) setCurriculum(urlCurriculum);

        if (auto === 'true' && urlTopic && urlGrade && urlCurriculum && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            // Delay slightly to ensure states are set
            setTimeout(() => {
                handleGenerate();
            }, 500);
        }
    }, []);

    const handleDownloadPPTX = () => {
        if (!generatedPPT) return;

        try {
            const pres = new pptxgen();
            pres.title = generatedPPT.title;

            generatedPPT.slides.forEach((slide: any) => {
                const pptSlide = pres.addSlide();

                // Background
                if (slide.image) {
                    pptSlide.background = { path: slide.image };
                } else if (slide.layout === 'organic_title' || slide.layout === 'thank_you') {
                    pptSlide.background = { color: '409c95' };
                } else {
                    pptSlide.background = { color: 'f8fafc' };
                }

                // Add Title
                pptSlide.addText(slide.title, {
                    x: 0.5,
                    y: 0.5,
                    w: '90%',
                    h: 1,
                    fontSize: 44,
                    bold: true,
                    color: slide.layout === 'timeline_process' ? 'FFFFFF' : 'FFFFFF',
                    align: 'center',
                    valign: 'middle',
                    inset: 1
                });

                // Add Content/Body
                if (slide.content && Array.isArray(slide.content)) {
                    const bodyText = slide.content.map((point: string, i: number) => `${i + 1}. ${point}`).join('\n\n');
                    pptSlide.addText(bodyText, {
                        x: 0.7,
                        y: 1.8,
                        w: '80%',
                        h: 3,
                        fontSize: 18,
                        color: 'FFFFFF',
                        valign: 'top',
                        bullet: true
                    });
                }

                if (slide.subtitle_1) {
                    pptSlide.addText(slide.subtitle_1, {
                        x: 0.5,
                        y: 3.5,
                        w: '90%',
                        fontSize: 24,
                        color: 'fcd3b6',
                        align: 'center',
                        bold: true
                    });
                }

                if (slide.subtitle_2) {
                    pptSlide.addText(slide.subtitle_2, {
                        x: 0.5,
                        y: 4.2,
                        w: '90%',
                        fontSize: 16,
                        color: 'ecfdf5',
                        align: 'center'
                    });
                }
            });

            pres.writeFile({ fileName: `${generatedPPT.title.replace(/\s+/g, '_')}.pptx` });
            toast.success("Download Started", {
                description: "Your presentation is being downloaded.",
            });
        } catch (error) {
            console.error("PPT Generation Error:", error);
            toast.error("Download Failed", {
                description: "Failed to generate PowerPoint file.",
            });
        }
    };

    const handleShare = async () => {
        if (!generatedPPT) return;

        const baseUrl = window.location.origin + window.location.pathname;
        const shareUrl = `${baseUrl}?tab=ppt&topic=${encodeURIComponent(topic)}&grade=${encodeURIComponent(grade)}&curriculum=${encodeURIComponent(curriculum)}&autoGenerate=true`;

        const shareData = {
            title: `Check out this PPT on ${topic}`,
            text: `I generated a professional presentation on "${topic}" using Co-Teacher AI. Take a look!`,
            url: shareUrl
        };

        // 1. Try Native Share if on mobile
        if (navigator.share && /Android|iPhone|iPad/i.test(navigator.userAgent)) {
            try {
                await navigator.share(shareData);
                toast.success("Shared successfully!");
                return;
            } catch (err) {
                console.log("Native share failed or cancelled");
            }
        }

        // 2. Fallback: Copy Link
        navigator.clipboard.writeText(shareUrl);

        // 3. Open WhatsApp for Desktop/Web
        const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(shareData.text + " " + shareUrl)}`;
        window.open(whatsappUrl, '_blank');

        toast.success("Link Copied & WhatsApp Opened", {
            description: "Share link is ready in your clipboard and WhatsApp."
        });
    };

    return (
        <div className="space-y-6 max-w-6xl mx-auto px-4 sm:px-6 pb-20">
            {/* Header / Input Config Section */}
            <div className="flex flex-col lg:flex-row gap-6 lg:gap-8 items-stretch">
                <Card className="flex-1 bg-white/70 backdrop-blur-xl border-white/20 shadow-2xl overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-br from-indigo-50/50 to-white/50 -z-10" />
                    <CardHeader className="pb-2">
                        <CardTitle className="flex items-center gap-3 text-2xl font-bold bg-gradient-to-r from-indigo-600 to-violet-600 bg-clip-text text-transparent">
                            <Sparkles className="w-6 h-6 text-indigo-500" />
                            AI Presentation Generator
                        </CardTitle>
                        <CardDescription className="text-slate-500 font-medium">
                            Create professional, curriculum-aligned presentations in seconds.
                        </CardDescription>
                    </CardHeader>
                    <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6">
                        <div className="space-y-2">
                            <Label className="text-slate-700 font-semibold">Topic</Label>
                            <Input
                                placeholder="e.g. Solar System, Photosynthesis, WW2"
                                value={topic}
                                onChange={(e) => setTopic(e.target.value)}
                                className="h-11 border-slate-200 focus:border-indigo-500 focus:ring-indigo-500 bg-white shadow-sm transition-all"
                            />
                        </div>
                        <div className="space-y-2">
                            <Label className="text-slate-700 font-semibold">Curriculum</Label>
                            <Select value={curriculum} onValueChange={setCurriculum}>
                                <SelectTrigger className="h-11 border-slate-200 bg-white shadow-sm">
                                    <SelectValue placeholder="Select Curriculum" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="CBSE">CBSE</SelectItem>
                                    <SelectItem value="ICSE">ICSE</SelectItem>
                                    <SelectItem value="SSC">SSC</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                        <div className="space-y-2">
                            <Label className="text-slate-700 font-semibold">Grade Level</Label>
                            <Select value={grade} onValueChange={setGrade}>
                                <SelectTrigger className="h-11 border-slate-200 bg-white shadow-sm">
                                    <SelectValue placeholder="Select Class" />
                                </SelectTrigger>
                                <SelectContent>
                                    {Array.from({ length: 12 }, (_, i) => (i + 1).toString()).map(g => (
                                        <SelectItem key={g} value={g}>Grade {g}</SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                        <div className="space-y-2">
                            <Label className="text-slate-700 font-semibold">Number of Slides</Label>
                            <Select value={numSlides} onValueChange={setNumSlides}>
                                <SelectTrigger className="h-11 border-slate-200 bg-white shadow-sm">
                                    <SelectValue placeholder="5 Slides" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="3">3 Slides (Short)</SelectItem>
                                    <SelectItem value="5">5 Slides (Standard)</SelectItem>
                                    <SelectItem value="8">8 Slides (Detailed)</SelectItem>
                                    <SelectItem value="10">10 Slides (Comprehensive)</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                    </CardContent>
                </Card>

                <div className="w-full md:w-80 flex flex-col gap-4">
                    <Button
                        size="lg"
                        className="w-full h-20 text-xl font-bold bg-gradient-to-r from-indigo-600 to-indigo-700 hover:from-indigo-700 hover:to-indigo-800 shadow-[0_10px_40px_-10px_rgba(79,70,229,0.5)] transition-all hover:scale-[1.02] active:scale-95 text-white border-0"
                        onClick={handleGenerate}
                        disabled={isGenerating}
                    >
                        {isGenerating ? (
                            <div className="flex flex-col items-center gap-1">
                                <div className="flex items-center">
                                    <Loader2 className="mr-2 h-6 w-6 animate-spin" /> Generating...
                                </div>
                                <div className="w-32 h-1 bg-white/20 rounded-full mt-1 overflow-hidden">
                                    <motion.div
                                        className="h-full bg-white"
                                        animate={{ x: [-100, 100] }}
                                        transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                                    />
                                </div>
                            </div>
                        ) : (
                            <>
                                <Sparkles className="mr-2 h-6 w-6" /> Generate PPT
                            </>
                        )}
                    </Button>
                    <div className="bg-indigo-50/80 backdrop-blur-md p-6 rounded-2xl border border-indigo-100 shadow-sm space-y-4">
                        <div className="flex items-center gap-2 font-bold text-indigo-900 border-b border-indigo-200 pb-2 uppercase tracking-tighter">
                            <Layers className="w-5 h-5 text-indigo-500" /> Pro Features Active
                        </div>
                        <ul className="space-y-3">
                            <li className="flex items-center gap-2 text-sm text-indigo-700 font-medium">
                                <div className="w-1.5 h-1.5 rounded-full bg-indigo-400" />
                                HD Unsplash Images
                            </li>
                            <li className="flex items-center gap-2 text-sm text-indigo-700 font-medium">
                                <div className="w-1.5 h-1.5 rounded-full bg-indigo-400" />
                                Smart Layout Engine
                            </li>
                            <li className="flex items-center gap-2 text-sm text-indigo-700 font-medium">
                                <div className="w-1.5 h-1.5 rounded-full bg-indigo-400" />
                                Auto-Theming
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            {/* PREVIEW AREA */}
            <AnimatePresence>
                {generatedPPT && (
                    <motion.div
                        initial={{ opacity: 0, y: 40 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0 }}
                        className="space-y-8"
                    >
                        <div className="flex items-center justify-between border-b pb-4">
                            <div>
                                <h2 className="text-2xl font-bold text-slate-900">Generated Presentation</h2>
                                <p className="text-slate-500 text-sm mt-1">{generatedPPT.title}</p>
                            </div>
                            <div className="flex gap-2">
                                <Button
                                    onClick={handleDownloadPPTX}
                                    className="bg-[#4F46E5] hover:bg-[#4338ca] text-white gap-2 shadow-sm"
                                >
                                    <Download className="w-4 h-4" /> Download .PPTX
                                </Button>
                                <Button
                                    variant="outline"
                                    onClick={handleShare}
                                    className="gap-2"
                                >
                                    <Share2 className="w-4 h-4" /> Share
                                </Button>
                            </div>
                        </div>

                        <div className="flex flex-col gap-12 max-w-4xl mx-auto">
                            {generatedPPT.slides.map((slide: any, idx: number) => (
                                <motion.div
                                    key={idx}
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: idx * 0.1 }}
                                    className="relative group perspective-1000"
                                >
                                    <div className="absolute -top-3 left-0 bg-slate-900 text-white text-xs font-bold px-3 py-1 rounded-t-lg z-10">
                                        Slide {idx + 1}
                                    </div>

                                    {/* Slide Container - Responsive Aspect Ratio */}
                                    <div className="bg-black border-2 sm:border-4 border-slate-900 rounded-xl overflow-hidden aspect-video shadow-2xl flex flex-col relative text-white text-[6px] sm:text-[10px] md:text-base">

                                        {/* Common Background: Clean Professional Look */}
                                        <div className="absolute inset-0 z-0 overflow-hidden">
                                            {/* Solid Professional Teal for Title & Thank You */}
                                            {(slide.layout === 'organic_title' || slide.layout === 'thank_you') && (
                                                <div className="absolute inset-0 bg-[#409c95]"></div>
                                            )}

                                            {/* Clean Background for Timeline/Process */}
                                            {slide.layout === 'timeline_process' && (
                                                <div className="absolute inset-0">
                                                    <img src={slide.image} alt="Background" className="w-full h-full object-cover transform scale-110 transition-transform duration-[10000ms] ease-out" />
                                                    {/* Lighter overlay to show image more clearly */}
                                                    <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-[1px]"></div>
                                                </div>
                                            )}
                                        </div>

                                        {/* SLIDE TYPE 1: PROFESSIONAL TITLE SLIDE (Text Only) */}
                                        {slide.layout === 'organic_title' && (
                                            <div className="flex-1 relative z-10 flex flex-col items-center justify-center p-6 sm:p-12 lg:p-16 h-full text-center">
                                                <div className="max-w-4xl">
                                                    <h1 className="text-2xl sm:text-5xl lg:text-7xl font-black text-white leading-tight mb-4 sm:mb-8 drop-shadow-lg tracking-tight">
                                                        {slide.title}
                                                    </h1>
                                                    <div className="w-24 sm:w-48 bg-[#df9b58] h-1 sm:h-2 mb-6 sm:mb-10 mx-auto rounded-full shadow-lg"></div>
                                                    <p className="text-base sm:text-2xl lg:text-3xl text-[#fcd3b6] font-bold mb-2 sm:mb-4 tracking-wide uppercase drop-shadow-md">{slide.subtitle_1 || 'Grade 10 • CBSE'}</p>
                                                    <p className="text-[10px] sm:text-base lg:text-xl text-emerald-50 font-medium tracking-widest uppercase">{slide.subtitle_2 || 'Presented by Co-Teacher AI'}</p>
                                                </div>
                                            </div>
                                        )}

                                        {/* SLIDE TYPE 2: CONTENT SLIDES (With Variations) */}
                                        {(slide.layout === 'timeline_process' || slide.layout === 'centered_visual' || slide.layout === 'process_steps' || slide.layout === 'comparison_view') && (
                                            <div className="flex-1 flex items-stretch">
                                                {slide.layout === 'timeline_process' ? (
                                                    /* VARIATION 1: Split Layout (Text Left / Image Right) - For Visual Interest */
                                                    <div className="flex w-full h-full">
                                                        {/* Text Side (60%) */}
                                                        <div className="w-[60%] p-4 sm:p-8 lg:p-12 flex flex-col justify-center space-y-3 sm:space-y-6 lg:space-y-8 bg-white z-20 shadow-2xl overflow-hidden">
                                                            <div className="mb-0.5 sm:mb-2">
                                                                {slide.tag && (
                                                                    <span className={`inline-block px-4 py-1 rounded-full text-xs font-bold uppercase tracking-widest mb-4 text-white
                                                                        ${slide.theme === 'blue' ? 'bg-blue-500' :
                                                                            slide.theme === 'orange' ? 'bg-orange-500' :
                                                                                slide.theme === 'purple' ? 'bg-purple-500' :
                                                                                    slide.theme === 'emerald' ? 'bg-emerald-500' :
                                                                                        slide.theme === 'rose' ? 'bg-rose-500' : 'bg-[#345d67]'}`}>
                                                                        {slide.tag}
                                                                    </span>
                                                                )}
                                                                <h3 className={`text-5xl font-black tracking-tight leading-tight
                                                                    ${slide.theme === 'blue' ? 'text-blue-900' :
                                                                        slide.theme === 'orange' ? 'text-orange-900' :
                                                                            slide.theme === 'purple' ? 'text-purple-900' :
                                                                                slide.theme === 'emerald' ? 'text-emerald-900' :
                                                                                    slide.theme === 'rose' ? 'text-rose-900' : 'text-[#345d67]'}`}>
                                                                    {slide.title}
                                                                </h3>
                                                            </div>

                                                            <div className="space-y-6">
                                                                {slide.content.slice(0, 3).map((point: string, i: number) => (
                                                                    <div key={i} className="flex gap-4">
                                                                        <div className={`w-12 h-12 shrink-0 rounded-xl flex items-center justify-center text-white font-bold text-lg shadow-md mt-1
                                                                            ${slide.theme === 'blue' ? 'bg-blue-600' :
                                                                                slide.theme === 'orange' ? 'bg-orange-600' :
                                                                                    slide.theme === 'purple' ? 'bg-purple-600' :
                                                                                        slide.theme === 'emerald' ? 'bg-emerald-600' :
                                                                                            slide.theme === 'rose' ? 'bg-rose-600' : 'bg-[#345d67]'}`}>
                                                                            0{i + 1}
                                                                        </div>
                                                                        <p className="text-slate-600 text-lg font-medium leading-relaxed">{point}</p>
                                                                    </div>
                                                                ))}
                                                            </div>

                                                            {/* Activity Highlight Box */}
                                                            {slide.activity && (
                                                                <div className="mt-4 p-4 rounded-2xl bg-indigo-50 border-l-4 border-indigo-400">
                                                                    <div className="flex items-center gap-2 mb-1 text-indigo-900 font-bold text-sm">
                                                                        <MessageCircle className="w-4 h-4" /> CLASSROOM ACTIVITY
                                                                    </div>
                                                                    <p className="text-indigo-800 text-sm italic font-medium">"{slide.activity}"</p>
                                                                </div>
                                                            )}
                                                        </div>

                                                        {/* Image Side (40%) */}
                                                        <div className="w-[40%] relative overflow-hidden">
                                                            <div className={`absolute inset-0 opacity-20 bg-black`}></div>
                                                            <img
                                                                src={slide.fullImage}
                                                                alt="Slide Visual"
                                                                className="w-full h-full object-cover transform hover:scale-105 transition-transform duration-1000"
                                                            />
                                                            {/* Overlay Gradient */}
                                                            <div className={`absolute inset-0 bg-gradient-to-r from-white via-transparent to-transparent opacity-100`}></div>
                                                        </div>
                                                    </div>
                                                ) : slide.layout === 'process_steps' ? (
                                                    /* NEW: Process Steps Layout */
                                                    <div className="w-full flex flex-col p-16 gap-12 bg-slate-50">
                                                        <div className="text-center space-y-4">
                                                            <h3 className="text-5xl font-black text-slate-900 tracking-tighter">{slide.title}</h3>
                                                            <p className="text-xl text-slate-500 font-medium italic">{slide.subtitle}</p>
                                                        </div>
                                                        <div className="grid grid-cols-4 gap-6">
                                                            {slide.content.map((point: string, i: number) => (
                                                                <div key={i} className="bg-white p-8 rounded-3xl shadow-xl border border-slate-100 relative group hover:-translate-y-2 transition-all">
                                                                    <div className={`w-14 h-14 rounded-full flex items-center justify-center text-white font-black text-2xl mb-6 
                                                                        ${slide.theme === 'blue' ? 'bg-blue-600 shadow-blue-200' : 'bg-indigo-600 shadow-indigo-200'} shadow-xl`}>
                                                                        {i + 1}
                                                                    </div>
                                                                    <p className="text-slate-700 font-bold leading-snug">{point}</p>
                                                                </div>
                                                            ))}
                                                        </div>
                                                        {slide.activity && (
                                                            <div className="bg-indigo-600 text-white p-6 rounded-3xl flex items-center gap-6 shadow-2xl">
                                                                <div className="bg-white/20 p-4 rounded-2xl"><Sparkles /></div>
                                                                <div>
                                                                    <p className="text-xs font-black opacity-70 uppercase tracking-widest">Exercise</p>
                                                                    <p className="text-xl font-bold italic">"{slide.activity}"</p>
                                                                </div>
                                                            </div>
                                                        )}
                                                    </div>
                                                ) : slide.layout === 'comparison_view' ? (
                                                    /* NEW: Comparison View Layout */
                                                    <div className="w-full flex p-16 gap-12 bg-white">
                                                        <div className="flex-1 space-y-8">
                                                            <h3 className="text-5xl font-black text-slate-900 border-l-8 border-indigo-600 pl-6 leading-none">{slide.title}</h3>
                                                            <div className="grid grid-cols-2 gap-8">
                                                                {slide.content.map((point: string, i: number) => (
                                                                    <div key={i} className="p-6 rounded-2xl bg-slate-50 border border-slate-200 hover:border-indigo-400 transition-colors">
                                                                        <p className="text-slate-700 font-medium leading-relaxed">{point}</p>
                                                                    </div>
                                                                ))}
                                                            </div>
                                                            {slide.activity && (
                                                                <div className="p-6 rounded-2xl bg-amber-50 border border-amber-200 text-amber-900">
                                                                    <p className="text-xs font-black uppercase mb-2">Discussion Starter</p>
                                                                    <p className="font-bold italic text-lg">"{slide.activity}"</p>
                                                                </div>
                                                            )}
                                                        </div>
                                                        <div className="w-1/3 rounded-[3rem] overflow-hidden shadow-2xl border-8 border-white">
                                                            <img src={slide.fullImage} className="w-full h-full object-cover" alt="Visual" />
                                                        </div>
                                                    </div>
                                                ) : (
                                                    /* VARIATION 2: Centered Layout (Pro Visual Version) */
                                                    <div className="w-full max-w-5xl flex flex-col justify-center gap-10 p-16 relative z-10">

                                                        {/* Large Centered Visual Card */}
                                                        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-[80%] opacity-10 bg-white/5 rounded-3xl -z-10 border border-white/10 blur-xl"></div>

                                                        {/* Header Section with Tag */}
                                                        <div className="text-center mb-8">
                                                            {slide.tag && (
                                                                <span className={`inline-block px-5 py-1.5 rounded-full text-xs font-black uppercase tracking-widest mb-6 text-white shadow-lg
                                                                    ${slide.theme === 'blue' ? 'bg-blue-500 shadow-blue-500/20' :
                                                                        slide.theme === 'orange' ? 'bg-orange-500 shadow-orange-500/20' :
                                                                            slide.theme === 'purple' ? 'bg-purple-500 shadow-purple-500/20' :
                                                                                slide.theme === 'emerald' ? 'bg-emerald-500 shadow-emerald-500/20' :
                                                                                    slide.theme === 'rose' ? 'bg-rose-500 shadow-rose-500/20' : 'bg-[#345d67]'}`}>
                                                                    {slide.tag}
                                                                </span>
                                                            )}
                                                            <h3 className="text-6xl font-black mb-4 tracking-tight text-white drop-shadow-2xl">
                                                                {slide.title}
                                                            </h3>
                                                            <div className="flex justify-center flex-wrap gap-4 mt-8">
                                                                {slide.content.slice(0, 3).map((point: string, i: number) => (
                                                                    <div key={i} className="flex-1 min-w-[300px] bg-white/10 backdrop-blur-md p-8 rounded-3xl border border-white/20 shadow-2xl hover:bg-white/15 transition-all group overflow-hidden relative text-left">
                                                                        <div className="absolute -top-4 -right-4 w-16 h-16 bg-white/5 rounded-full blur-xl group-hover:bg-white/10 transition-all"></div>
                                                                        <div className={`w-12 h-12 rounded-xl flex items-center justify-center text-white font-black text-xl mb-6 shadow-lg
                                                                            ${slide.theme === 'blue' ? 'bg-blue-600' :
                                                                                slide.theme === 'orange' ? 'bg-orange-600' :
                                                                                    slide.theme === 'purple' ? 'bg-purple-600' :
                                                                                        slide.theme === 'emerald' ? 'bg-emerald-600' :
                                                                                            slide.theme === 'rose' ? 'bg-rose-600' : 'bg-[#345d67]'}`}>
                                                                            0{i + 1}
                                                                        </div>
                                                                        <p className="text-indigo-50 text-xl font-bold leading-relaxed">{point}</p>
                                                                    </div>
                                                                ))}
                                                            </div>

                                                            {slide.activity && (
                                                                <div className="mt-8 mx-auto max-w-2xl p-6 rounded-3xl bg-white/10 backdrop-blur-md border border-white/20 shadow-2xl">
                                                                    <div className="flex items-center justify-center gap-2 mb-2 text-indigo-300 font-black text-xs uppercase tracking-widest">
                                                                        <MessageCircle className="w-5 h-5" /> ACTIVITY / DISCUSSION
                                                                    </div>
                                                                    <p className="text-white text-xl italic font-bold leading-relaxed text-center">"{slide.activity}"</p>
                                                                </div>
                                                            )}
                                                        </div>
                                                    </div>
                                                )}
                                            </div>
                                        )}

                                        {/* SLIDE TYPE 3: THANK YOU / CONTACT (Topnotch Pro Version) */}
                                        {slide.layout === 'thank_you' && (
                                            <div className="flex-1 relative z-10 flex flex-col items-center justify-center p-16 h-full text-center overflow-hidden">

                                                {/* Background Image Overlay */}
                                                <div className="absolute inset-0 opacity-20">
                                                    <img
                                                        src={slide.image}
                                                        alt="Background"
                                                        className="w-full h-full object-cover blur-sm transform scale-105"
                                                    />
                                                    <div className="absolute inset-0 bg-[#345d67]/90 mix-blend-multiply"></div>
                                                </div>

                                                <div className="relative z-10 flex flex-col items-center">
                                                    <h1 className="text-9xl font-black text-white mb-8 drop-shadow-2xl tracking-tighter">Thank You</h1>
                                                    <div className="w-48 h-2 bg-gradient-to-r from-[#df9b58] to-[#fcd3b6] rounded-full shadow-lg opacity-90"></div>
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                </motion.div>
                            ))}
                            <Button variant="ghost" className="border-2 border-dashed border-slate-300 h-24 hover:bg-slate-50 hover:border-indigo-300 text-slate-500 font-bold rounded-xl">
                                <Plus className="w-6 h-6 mr-2" /> Add New Slide
                            </Button>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}
