import React, { useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
    Loader2, Download, Share2, Plus, Sparkles, Wand2, Layers,
    Presentation, Copy, Check, MessageCircle, Share, Eye
} from "lucide-react";
import pptxgen from "pptxgenjs";
import { useToast } from "@/components/ui/use-toast";
import { motion, AnimatePresence } from "framer-motion";

import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { FileText, ClipboardCheck, History, Clock, FileType, Search as SearchIcon, Printer, Trash2 } from "lucide-react";
import api from "@/api/client";
import { toast } from "sonner";

export function PPTGeneratorTab() {
    const { toast: uiToast } = useToast();
    const [topic, setTopic] = useState('');
    const [grade, setGrade] = useState('');
    const [numSlides, setNumSlides] = useState('5');
    const [curriculum, setCurriculum] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedPPT, setGeneratedPPT] = useState<any>(null);
    const hasAutoGenerated = useRef(false);
    const [activeTab, setActiveTab] = useState('list');
    const [viewingPresentation, setViewingPresentation] = useState<any>(null);
    const [generationProgress, setGenerationProgress] = useState(0);
    const [searchTerm, setSearchTerm] = useState('');
    const queryClient = useQueryClient();

    const handleGenerate = async () => {
        if (!topic || !grade || !curriculum) {
            toast.error("Missing Information", {
                description: "Please fill in all required fields to generate the presentation."
            });
            return;
        }

        const token = localStorage.getItem('token');
        if (!token) {
            toast.error("Authentication Error", {
                description: "You've been signed out. Please login again.",
            });
            window.location.href = '/login?expired=true';
            return;
        }

        // Trial Limit Check: Block if user has already created something
        try {
            const statsRes = await api.get('/dashboard/stats');
            const lessonsCount = statsRes.data.lessonsCreated || 0;
            if (lessonsCount >= 1) {
                toast.error("Free trial limit reached (1 resource). Upgrade to create more!", {
                    description: "You've used your 1 free AI generation.",
                });
                return;
            }
        } catch (err) {
            console.error("Stats check failed", err);
            if ((err as any).response?.status === 401) return;
        }

        setIsGenerating(true);
        setGeneratedPPT(null);
        setGenerationProgress(0);

        // Progress simulation for UI feel
        const progressInterval = setInterval(() => {
            setGenerationProgress(prev => {
                if (prev >= 90) {
                    clearInterval(progressInterval);
                    return 90;
                }
                return prev + Math.random() * 10;
            });
        }, 800);

        try {
            const response = await api.post('/lessons/generate-ppt', {
                topic,
                grade,
                curriculum,
                slides: numSlides
            });

            const aiSlides = response.data;

            // Map AI slides to presentation format
            const formattedSlides = aiSlides.map((s: any, idx: number) => {
                let layout = "timeline_process";
                const type = (s.layout_type || '').toLowerCase();

                if (type === 'title') layout = "organic_title";
                else if (type === 'summary' || idx === aiSlides.length - 1) layout = "thank_you";
                else if (type === 'process') layout = "process_steps";
                else if (type === 'comparison') layout = "comparison_view";
                else if (type === 'intro') layout = "timeline_process";
                else layout = idx % 2 === 0 ? "timeline_process" : "centered_visual";

                // Map theme colors
                const themes = ['blue', 'orange', 'purple', 'emerald', 'rose'];
                const theme = themes[idx % themes.length];

                return {
                    ...s,
                    subtitle_1: s.subtitle || `GRADE ${grade} • ${curriculum.toUpperCase()}`,
                    subtitle_2: s.activity || "Presented by Co-Teacher AI",
                    layout,
                    theme,
                    image: s.image_url || `https://source.unsplash.com/featured/1600x900?${encodeURIComponent(s.image_keyword || topic)}`,
                    fullImage: s.image_url || `https://source.unsplash.com/featured/1600x900?${encodeURIComponent(s.image_keyword || topic)}`,
                    tag: type.toUpperCase() || "CONTENT"
                };
            });

            setGeneratedPPT({
                title: `${topic} (${curriculum.toUpperCase()} - Grade ${grade})`,
                slides: formattedSlides
            });

            clearInterval(progressInterval);
            setGenerationProgress(100);
            queryClient.invalidateQueries({ queryKey: ['lessons'] });
            toast.success("Success", {
                description: "Your presentation has been saved to your library."
            });
        } catch (error) {
            console.error("PPT Generation Error:", error);
            toast.error("Generation Failed", {
                description: "There was an error generating your presentation. Please try again."
            });
        } finally {
            setIsGenerating(false);
        }
    };

    useEffect(() => {
        const params = new URLSearchParams(window.location.search);
        const urlTopic = params.get('topic');
        const urlGrade = params.get('grade');
        const urlCurriculum = params.get('curriculum');
        const auto = params.get('autoGenerate');

        if (urlTopic) setTopic(urlTopic);
        if (urlGrade) setGrade(urlGrade);
        if (urlCurriculum) setCurriculum(urlCurriculum);

        if (auto === 'true' && urlTopic && urlGrade && urlCurriculum && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            // Delay slightly to ensure states are set
            setTimeout(() => {
                handleGenerate();
            }, 500);
        }
    }, []);

    const handleDownloadPPTX = (presentationData?: any) => {
        const ppt = presentationData?.content || presentationData || generatedPPT;
        if (!ppt) return;

        try {
            const pres = new pptxgen();
            pres.title = ppt.title;

            ppt.slides.forEach((slide: any) => {
                const pptSlide = pres.addSlide();

                // Background
                if (slide.image) {
                    pptSlide.background = { path: slide.image };
                } else if (slide.layout === 'organic_title' || slide.layout === 'thank_you') {
                    pptSlide.background = { color: '409c95' };
                } else {
                    pptSlide.background = { color: 'f8fafc' };
                }

                // Add Title
                pptSlide.addText(slide.title, {
                    x: 0.5,
                    y: 0.5,
                    w: '90%',
                    h: 1,
                    fontSize: 44,
                    bold: true,
                    color: slide.layout === 'timeline_process' ? 'FFFFFF' : 'FFFFFF',
                    align: 'center',
                    valign: 'middle',
                    inset: 1
                });

                // Add Content/Body
                if (slide.content && Array.isArray(slide.content)) {
                    const bodyText = slide.content.map((point: string, i: number) => `${i + 1}. ${point}`).join('\n\n');
                    pptSlide.addText(bodyText, {
                        x: 0.7,
                        y: 1.8,
                        w: '80%',
                        h: 3,
                        fontSize: 18,
                        color: 'FFFFFF',
                        valign: 'top',
                        bullet: true
                    });
                }

                if (slide.subtitle_1) {
                    pptSlide.addText(slide.subtitle_1, {
                        x: 0.5,
                        y: 3.5,
                        w: '90%',
                        fontSize: 24,
                        color: 'fcd3b6',
                        align: 'center',
                        bold: true
                    });
                }

                if (slide.subtitle_2) {
                    pptSlide.addText(slide.subtitle_2, {
                        x: 0.5,
                        y: 4.2,
                        w: '90%',
                        fontSize: 16,
                        color: 'ecfdf5',
                        align: 'center'
                    });
                }
            });

            pres.writeFile({ fileName: `${ppt.title.replace(/\s+/g, '_')}.pptx` });
            toast.success("Download Started", {
                description: "Your presentation is being downloaded.",
            });
        } catch (error) {
            console.error("PPT Generation Error:", error);
            toast.error("Download Failed", {
                description: "Failed to generate PowerPoint file.",
            });
        }
    };

    const handleShare = async (presentationData?: any) => {
        const ppt = presentationData?.content || presentationData || generatedPPT;
        if (!ppt) return;

        const baseUrl = window.location.origin + window.location.pathname;
        const shareUrl = `${baseUrl}?tab=ppt&topic=${encodeURIComponent(presentationData?.topic || topic)}&grade=${encodeURIComponent(presentationData?.grade || grade)}&curriculum=${encodeURIComponent(presentationData?.curriculum || curriculum)}&autoGenerate=true`;

        const shareData = {
            title: `Check out this PPT on ${topic}`,
            text: `I generated a professional presentation on "${topic}" using Co-Teacher AI. Take a look!`,
            url: shareUrl
        };

        // 1. Try Native Share if on mobile
        if (navigator.share && /Android|iPhone|iPad/i.test(navigator.userAgent)) {
            try {
                await navigator.share(shareData);
                toast.success("Shared successfully!");
                return;
            } catch (err) {
                console.log("Native share failed or cancelled");
            }
        }

        // 2. Fallback: Copy Link
        navigator.clipboard.writeText(shareUrl);

        // 3. Open WhatsApp for Desktop/Web
        const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(shareData.text + " " + shareUrl)}`;
        window.open(whatsappUrl, '_blank');

        toast.success("Link Copied & WhatsApp Opened", {
            description: "Share link is ready in your clipboard and WhatsApp."
        });
    };

    const { data: presentations, isLoading: isLoadingList } = useQuery({
        queryKey: ['lessons'],
        queryFn: async () => {
            const res = await api.get('/lessons');
            return res.data.filter((l: any) => l.type === 'PRESENTATION');
        }
    });

    const deleteMutation = (id: string) => {
        toast.promise(api.delete(`/lessons/${id}`), {
            loading: 'Deleting presentation...',
            success: () => {
                queryClient.invalidateQueries({ queryKey: ['lessons'] });
                return 'Presentation deleted successfully';
            },
            error: 'Failed to delete presentation'
        });
    };

    const filteredPresentations = presentations?.filter((ppt: any) =>
        ppt.title?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        ppt.topic?.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div className="space-y-6 max-w-6xl mx-auto pb-20">
            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
                    <div>
                        <h2 className="text-3xl font-black text-slate-900 tracking-tight font-display">PowerPoint Generator</h2>
                        <p className="text-slate-500 font-medium">Create and manage your AI-powered presentations</p>
                    </div>

                    <div className="flex flex-col sm:flex-row items-center gap-4">
                        <div className="relative w-full sm:w-64">
                            <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                            <Input
                                placeholder="Search presentations..."
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                                className="pl-10 h-10 border-slate-200 bg-white/50 focus:bg-white transition-all rounded-xl text-xs font-bold"
                            />
                        </div>
                        <TabsList className="bg-slate-100/80 p-1 rounded-xl w-fit h-12">
                            <TabsTrigger
                                value="list"
                                className="rounded-lg font-bold px-6 data-[state=active]:bg-white data-[state=active]:text-indigo-600 data-[state=active]:shadow-sm h-10"
                            >
                                <History className="w-4 h-4 mr-2" /> My Presentations
                            </TabsTrigger>
                            <TabsTrigger
                                value="generator"
                                className="rounded-lg font-bold px-6 data-[state=active]:bg-white data-[state=active]:text-indigo-600 data-[state=active]:shadow-sm h-10"
                            >
                                <Plus className="w-4 h-4 mr-2" /> Create New
                            </TabsTrigger>
                        </TabsList>
                    </div>
                </div>

                <TabsContent value="list" className="mt-0">
                    {isLoadingList ? (
                        <div className="flex flex-col items-center justify-center py-24 gap-4">
                            <Loader2 className="w-12 h-12 text-indigo-500 animate-spin" />
                            <p className="text-slate-500 font-bold">Loading your library...</p>
                        </div>
                    ) : filteredPresentations && filteredPresentations.length > 0 ? (
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {filteredPresentations.map((ppt: any) => (
                                <Card
                                    key={ppt.id}
                                    className="group hover:shadow-xl transition-all border-slate-100 overflow-hidden cursor-pointer relative"
                                    onClick={() => setViewingPresentation(ppt)}
                                >
                                    <div className="aspect-video bg-indigo-50 relative overflow-hidden">
                                        {ppt.content?.slides?.[0]?.image ? (
                                            <img
                                                src={ppt.content.slides[0].image}
                                                alt={ppt.title}
                                                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                                            />
                                        ) : (
                                            <div className="w-full h-full flex items-center justify-center">
                                                <Presentation className="w-12 h-12 text-indigo-200" />
                                            </div>
                                        )}
                                        <div className="absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                                            <Button variant="secondary" className="font-bold shadow-xl">
                                                <Eye className="w-4 h-4 mr-2" /> View Slides
                                            </Button>
                                        </div>
                                        <div className="absolute top-2 right-2 flex gap-2">
                                            <span className="bg-white/90 backdrop-blur-sm text-[10px] font-black px-2 py-0.5 rounded-full text-indigo-600 border border-indigo-100">
                                                {ppt.content?.slides?.length || 0} SLIDES
                                            </span>
                                            <Button
                                                variant="destructive"
                                                size="icon"
                                                className="w-7 h-7 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity"
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    deleteMutation(ppt.id);
                                                }}
                                            >
                                                <Trash2 className="w-3.5 h-3.5" />
                                            </Button>
                                        </div>
                                    </div>
                                    <CardContent className="p-5">
                                        <h3 className="font-bold text-slate-900 group-hover:text-indigo-600 transition-colors line-clamp-1 mb-2">
                                            {ppt.title}
                                        </h3>
                                        <div className="flex items-center justify-between text-xs text-slate-400 font-bold uppercase tracking-wider">
                                            <div className="flex items-center gap-1">
                                                <Clock className="w-3 h-3" />
                                                {new Date(ppt.createdAt).toLocaleDateString()}
                                            </div>
                                            <span className="text-indigo-400">
                                                {ppt.grade ? `Grade ${ppt.grade}` : 'Resource'}
                                            </span>
                                        </div>
                                    </CardContent>
                                </Card>
                            ))}
                        </div>
                    ) : searchTerm ? (
                        <div className="py-32 text-center bg-white rounded-3xl border border-slate-100 shadow-sm relative overflow-hidden">
                            <div className="absolute top-0 right-0 w-32 h-32 bg-slate-50 rounded-full blur-3xl -z-10" />
                            <div className="w-20 h-20 bg-slate-50 rounded-2xl flex items-center justify-center mx-auto mb-6 transform rotate-3 shadow-inner">
                                <SearchIcon className="w-10 h-10 text-slate-300" />
                            </div>
                            <h3 className="text-2xl font-black text-slate-900 mb-2">No results found</h3>
                            <p className="text-slate-500 font-medium">We couldn't find any presentations matching <span className="text-indigo-600 font-bold">"{searchTerm}"</span></p>
                            <Button
                                variant="outline"
                                onClick={() => setSearchTerm('')}
                                className="mt-8 font-bold border-slate-200 rounded-xl hover:bg-slate-50 px-8"
                            >
                                Clear search and see all
                            </Button>
                        </div>
                    ) : (
                        <Card className="border-2 border-dashed border-slate-200 bg-white p-20 flex flex-col items-center justify-center text-center relative overflow-hidden group">
                            <div className="absolute inset-0 bg-gradient-to-br from-indigo-50/50 to-white pointer-events-none" />
                            <div className="absolute -right-20 -bottom-20 w-64 h-64 bg-indigo-100 rounded-full blur-3xl opacity-20 pointer-events-none group-hover:scale-110 transition-transform duration-700" />

                            <div className="relative z-10">
                                <div className="w-24 h-24 bg-white rounded-3xl flex items-center justify-center shadow-xl border border-slate-100 mb-8 mx-auto transform group-hover:scale-110 group-hover:rotate-6 transition-all duration-500">
                                    <Presentation className="w-12 h-12 text-indigo-500" />
                                </div>
                                <h3 className="text-3xl font-black text-slate-900 mb-3 tracking-tight">Your Library is Empty</h3>
                                <p className="text-slate-500 font-medium max-w-sm mb-10 mx-auto text-lg leading-relaxed">
                                    Create stunning, curriculum-aligned presentations for your class in seconds with AI.
                                </p>
                                <Button
                                    onClick={() => setActiveTab('generator')}
                                    className="bg-indigo-600 hover:bg-indigo-700 font-bold rounded-2xl px-10 h-14 text-lg shadow-xl shadow-indigo-200/50 transition-all hover:scale-105 active:scale-95"
                                >
                                    <Plus className="w-5 h-5 mr-3" /> Create First Presentation
                                </Button>
                            </div>

                            {/* Decorative mock presentation cards in background */}
                            <div className="absolute left-8 top-1/2 -translate-y-1/2 w-48 aspect-video bg-white/40 border border-slate-100 rounded-xl shadow-sm rotate-[-12deg] -z-10 blur-[1px]" />
                            <div className="absolute right-8 top-1/3 -translate-y-1/2 w-48 aspect-video bg-white/40 border border-slate-100 rounded-xl shadow-sm rotate-[15deg] -z-10 blur-[1px]" />
                        </Card>
                    )}
                </TabsContent>

                <TabsContent value="generator" className="mt-0">
                    <div className="space-y-6">
                        {/* Input Config Section */}
                        <div className="flex flex-col md:flex-row gap-8 items-stretch">
                            <Card className="flex-1 bg-white/70 backdrop-blur-xl border-white/20 shadow-2xl overflow-hidden">
                                <div className="absolute inset-0 bg-gradient-to-br from-indigo-50/50 to-white/50 -z-10" />
                                <CardHeader className="pb-2">
                                    <CardTitle className="flex items-center gap-3 text-2xl font-bold bg-gradient-to-r from-indigo-600 to-violet-600 bg-clip-text text-transparent">
                                        <Sparkles className="w-6 h-6 text-indigo-500" />
                                        AI Presentation Generator
                                    </CardTitle>
                                    <CardDescription className="text-slate-500 font-medium">
                                        Create professional, curriculum-aligned presentations in seconds.
                                    </CardDescription>
                                </CardHeader>
                                <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6">
                                    <div className="space-y-2">
                                        <Label className="text-slate-700 font-semibold">Topic</Label>
                                        <Input
                                            placeholder="e.g. Solar System, Photosynthesis, WW2"
                                            value={topic}
                                            onChange={(e) => setTopic(e.target.value)}
                                            className="h-11 border-slate-200 focus:border-indigo-500 focus:ring-indigo-500 bg-white shadow-sm transition-all"
                                        />
                                    </div>
                                    <div className="space-y-2">
                                        <Label className="text-slate-700 font-semibold">Curriculum</Label>
                                        <Select value={curriculum} onValueChange={setCurriculum}>
                                            <SelectTrigger className="h-11 border-slate-200 bg-white shadow-sm">
                                                <SelectValue placeholder="Select Curriculum" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="CBSE">CBSE</SelectItem>
                                                <SelectItem value="ICSE">ICSE</SelectItem>
                                                <SelectItem value="SSC">SSC</SelectItem>
                                            </SelectContent>
                                        </Select>
                                    </div>
                                    <div className="space-y-2">
                                        <Label className="text-slate-700 font-semibold">Grade Level</Label>
                                        <Select value={grade} onValueChange={setGrade}>
                                            <SelectTrigger className="h-11 border-slate-200 bg-white shadow-sm">
                                                <SelectValue placeholder="Select Class" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                {Array.from({ length: 12 }, (_, i) => (i + 1).toString()).map(g => (
                                                    <SelectItem key={g} value={g}>Grade {g}</SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                    </div>
                                    <div className="space-y-2">
                                        <Label className="text-slate-700 font-semibold">Number of Slides</Label>
                                        <Select value={numSlides} onValueChange={setNumSlides}>
                                            <SelectTrigger className="h-11 border-slate-200 bg-white shadow-sm">
                                                <SelectValue placeholder="5 Slides" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="3">3 Slides (Short)</SelectItem>
                                                <SelectItem value="5">5 Slides (Standard)</SelectItem>
                                                <SelectItem value="8">8 Slides (Detailed)</SelectItem>
                                                <SelectItem value="10">10 Slides (Comprehensive)</SelectItem>
                                            </SelectContent>
                                        </Select>
                                    </div>
                                </CardContent>
                            </Card>

                            <div className="w-full md:w-80 flex flex-col gap-4">
                                <Button
                                    size="lg"
                                    className="w-full h-20 text-xl font-bold bg-gradient-to-r from-indigo-600 to-indigo-700 hover:from-indigo-700 hover:to-indigo-800 shadow-[0_10px_40px_-10px_rgba(79,70,229,0.5)] transition-all hover:scale-[1.02] active:scale-95 text-white border-0"
                                    onClick={handleGenerate}
                                    disabled={isGenerating}
                                >
                                    {isGenerating ? (
                                        <div className="flex flex-col items-center gap-1">
                                            <div className="flex items-center">
                                                <Loader2 className="mr-2 h-6 w-6 animate-spin" /> Generating...
                                            </div>
                                            <div className="w-32 h-1 bg-white/20 rounded-full mt-1 overflow-hidden">
                                                <motion.div
                                                    className="h-full bg-white"
                                                    animate={{ x: [-100, 100] }}
                                                    transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                                                />
                                            </div>
                                        </div>
                                    ) : (
                                        <>
                                            <Sparkles className="mr-2 h-6 w-6" /> Generate PPT
                                        </>
                                    )}
                                </Button>
                                <div className="bg-indigo-50/80 backdrop-blur-md p-6 rounded-2xl border border-indigo-100 shadow-sm space-y-4">
                                    <div className="flex items-center gap-2 font-bold text-indigo-900 border-b border-indigo-200 pb-2 uppercase tracking-tighter">
                                        <Layers className="w-5 h-5 text-indigo-500" /> Pro Features Active
                                    </div>
                                    <ul className="space-y-3">
                                        <li className="flex items-center gap-2 text-sm text-indigo-700 font-medium">
                                            <div className="w-1.5 h-1.5 rounded-full bg-indigo-400" />
                                            HD Unsplash Images
                                        </li>
                                        <li className="flex items-center gap-2 text-sm text-indigo-700 font-medium">
                                            <div className="w-1.5 h-1.5 rounded-full bg-indigo-400" />
                                            Smart Layout Engine
                                        </li>
                                        <li className="flex items-center gap-2 text-sm text-indigo-700 font-medium">
                                            <div className="w-1.5 h-1.5 rounded-full bg-indigo-400" />
                                            Auto-Theming
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        {/* PREVIEW AREA */}
                        <AnimatePresence>
                            {generatedPPT && (
                                <motion.div
                                    initial={{ opacity: 0, y: 40 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0 }}
                                    className="space-y-8"
                                >
                                    <PresentationDisplay presentation={generatedPPT} onDownload={handleDownloadPPTX} onShare={handleShare} />
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>
                </TabsContent>
            </Tabs>

            {/* Viewing Dialog */}
            <Dialog open={!!viewingPresentation} onOpenChange={(open) => !open && setViewingPresentation(null)}>
                <DialogContent className="max-w-[95vw] w-[1400px] max-h-[95vh] overflow-y-auto p-0 border-none bg-slate-50">
                    <div className="p-8">
                        <div className="flex items-center justify-between mb-8">
                            <DialogHeader>
                                <DialogTitle className="text-3xl font-black text-slate-900 tracking-tight">
                                    {viewingPresentation?.title}
                                </DialogTitle>
                                <div className="flex items-center gap-4 text-sm text-slate-500 font-bold uppercase tracking-wider mt-1">
                                    <span className="bg-indigo-600 text-white px-3 py-1 rounded-lg">
                                        {viewingPresentation?.content?.slides?.length || 0} Slides
                                    </span>
                                    <span>{viewingPresentation?.grade ? `Class ${viewingPresentation.grade}` : ""}</span>
                                </div>
                            </DialogHeader>
                            <div className="flex gap-4">
                                <Button
                                    variant="outline"
                                    className="font-bold border-slate-200 h-12 px-6"
                                    onClick={() => handleDownloadPPTX(viewingPresentation)}
                                >
                                    <Download className="w-4 h-4 mr-2" /> Download PPTX
                                </Button>
                                <Button
                                    className="font-bold bg-indigo-600 h-12 px-8"
                                    onClick={() => handleShare(viewingPresentation)}
                                >
                                    <Share2 className="w-4 h-4 mr-2" /> Share Presentation
                                </Button>
                            </div>
                        </div>

                        {viewingPresentation && (
                            <PresentationDisplay presentation={viewingPresentation.content} isLibraryView />
                        )}
                    </div>
                </DialogContent>
            </Dialog>
        </div >
    );
}

function PresentationDisplay({ presentation, onDownload, onShare, isLibraryView = false }: { presentation: any, onDownload?: any, onShare?: any, isLibraryView?: boolean }) {
    return (
        <div className="space-y-8">
            {!isLibraryView && (
                <div className="flex items-center justify-between border-b border-slate-200 pb-4">
                    <div>
                        <h2 className="text-2xl font-bold text-slate-900">Preview Slides</h2>
                        <p className="text-slate-500 text-sm mt-1">{presentation.title}</p>
                    </div>
                    <div className="flex gap-2">
                        <Button
                            onClick={onDownload}
                            className="bg-[#4F46E5] hover:bg-[#4338ca] text-white gap-2 shadow-sm font-bold"
                        >
                            <Download className="w-4 h-4" /> Download .PPTX
                        </Button>
                        <Button
                            variant="outline"
                            onClick={onShare}
                            className="gap-2 font-bold border-slate-200"
                        >
                            <Share2 className="w-4 h-4" /> Share
                        </Button>
                    </div>
                </div>
            )}

            <div className="flex flex-col gap-12 max-w-4xl mx-auto">
                {presentation.slides?.map((slide: any, idx: number) => (
                    <motion.div
                        key={idx}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: idx * 0.1 }}
                        className="relative group "
                    >
                        <div className="absolute -top-3 left-4 bg-slate-900 text-white text-[10px] font-black uppercase tracking-widest px-4 py-1.5 rounded-t-xl z-10 shadow-lg">
                            Slide {idx + 1}
                        </div>

                        {/* Slide Container */}
                        <div className="bg-black border-4 border-slate-900 rounded-3xl overflow-hidden aspect-video shadow-2xl flex flex-col relative text-white ring-8 ring-white/50">

                            {/* Common Background: Clean Professional Look */}
                            <div className="absolute inset-0 z-0 overflow-hidden">
                                {/* Solid Professional Teal for Title & Thank You */}
                                {(slide.layout === 'organic_title' || slide.layout === 'thank_you') && (
                                    <div className="absolute inset-0 bg-[#409c95]"></div>
                                )}

                                {/* Clean Background for Timeline/Process */}
                                {slide.layout === 'timeline_process' && (
                                    <div className="absolute inset-0">
                                        <img src={slide.image} alt="Background" className="w-full h-full object-cover transform scale-110 transition-transform duration-[10000ms] ease-out" />
                                        <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-[1px]"></div>
                                    </div>
                                )}
                            </div>

                            {/* SLIDE TYPE 1: PROFESSIONAL TITLE SLIDE (Text Only) */}
                            {slide.layout === 'organic_title' && (
                                <div className="flex-1 relative z-10 flex flex-col items-center justify-center p-16 h-full text-center">
                                    <div className="max-w-4xl">
                                        <h1 className="text-7xl font-black text-white leading-tight mb-8 drop-shadow-lg tracking-tight">
                                            {slide.title}
                                        </h1>
                                        <div className="w-48 bg-[#df9b58] h-2 mb-10 mx-auto rounded-full shadow-lg"></div>
                                        <p className="text-3xl text-[#fcd3b6] font-bold mb-4 tracking-wide uppercase drop-shadow-md">{slide.subtitle_1 || 'General Topic'}</p>
                                        <p className="text-xl text-emerald-50 font-medium tracking-widest uppercase">{slide.subtitle_2 || 'Presented by Co-Teacher AI'}</p>
                                    </div>
                                </div>
                            )}

                            {/* SLIDE TYPE 2: CONTENT SLIDES (With Variations) */}
                            {(slide.layout === 'timeline_process' || slide.layout === 'centered_visual' || slide.layout === 'process_steps' || slide.layout === 'comparison_view') && (
                                <div className="flex-1 flex items-stretch">
                                    {slide.layout === 'timeline_process' ? (
                                        <div className="flex w-full h-full">
                                            {/* Text Side (60%) */}
                                            <div className="w-[60%] p-12 flex flex-col justify-center space-y-8 bg-white z-20 shadow-2xl">
                                                <div className="mb-2">
                                                    {slide.tag && (
                                                        <span className={`inline-block px-4 py-1 rounded-full text-[10px] font-black uppercase tracking-widest mb-4 text-white
                                                            ${slide.theme === 'blue' ? 'bg-blue-500' :
                                                                slide.theme === 'orange' ? 'bg-orange-500' :
                                                                    slide.theme === 'purple' ? 'bg-purple-500' :
                                                                        slide.theme === 'emerald' ? 'bg-emerald-500' :
                                                                            slide.theme === 'rose' ? 'bg-rose-500' : 'bg-[#345d67]'}`}>
                                                            {slide.tag}
                                                        </span>
                                                    )}
                                                    <h3 className={`text-4xl font-black tracking-tight leading-tight
                                                        ${slide.theme === 'blue' ? 'text-blue-900' :
                                                            slide.theme === 'orange' ? 'text-orange-900' :
                                                                slide.theme === 'purple' ? 'text-purple-900' :
                                                                    slide.theme === 'emerald' ? 'text-emerald-900' :
                                                                        slide.theme === 'rose' ? 'text-rose-900' : 'text-[#345d67]'}`}>
                                                        {slide.title}
                                                    </h3>
                                                </div>

                                                <div className="space-y-4">
                                                    {(Array.isArray(slide.content) ? slide.content : []).slice(0, 3).map((point: string, i: number) => (
                                                        <div key={i} className="flex gap-4">
                                                            <div className={`w-10 h-10 shrink-0 rounded-xl flex items-center justify-center text-white font-black text-lg shadow-md mt-1
                                                                ${slide.theme === 'blue' ? 'bg-blue-600' :
                                                                    slide.theme === 'orange' ? 'bg-orange-600' :
                                                                        slide.theme === 'purple' ? 'bg-purple-600' :
                                                                            slide.theme === 'emerald' ? 'bg-emerald-600' :
                                                                                slide.theme === 'rose' ? 'bg-rose-600' : 'bg-[#345d67]'}`}>
                                                                {i + 1}
                                                            </div>
                                                            <p className="text-slate-600 font-bold leading-relaxed">{point}</p>
                                                        </div>
                                                    ))}
                                                </div>

                                                {slide.activity && (
                                                    <div className="mt-4 p-4 rounded-2xl bg-indigo-50 border-l-4 border-indigo-400">
                                                        <div className="flex items-center gap-2 mb-1 text-indigo-900 font-black text-[10px] uppercase">
                                                            <MessageCircle className="w-4 h-4" /> Activity
                                                        </div>
                                                        <p className="text-indigo-800 text-sm italic font-bold">"{slide.activity}"</p>
                                                    </div>
                                                )}
                                            </div>

                                            {/* Image Side (40%) */}
                                            <div className="w-[40%] relative overflow-hidden">
                                                <img
                                                    src={slide.fullImage || slide.image}
                                                    alt="Slide Visual"
                                                    className="w-full h-full object-cover transform scale-110"
                                                />
                                                <div className={`absolute inset-0 bg-gradient-to-r from-white via-transparent to-transparent opacity-100`}></div>
                                            </div>
                                        </div>
                                    ) : (
                                        /* Simplified Fallback for other layouts in preview */
                                        <div className="flex-1 p-16 flex flex-col justify-center items-center text-center bg-white text-slate-900">
                                            <h3 className="text-5xl font-black mb-8 tracking-tight">{slide.title}</h3>
                                            <div className="flex flex-wrap justify-center gap-6 max-w-4xl">
                                                {(Array.isArray(slide.content) ? slide.content : []).map((point: string, i: number) => (
                                                    <div key={i} className="bg-slate-50 p-6 rounded-2xl border border-slate-100 font-bold text-slate-700 min-w-[200px]">
                                                        {point}
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            )}

                            {/* SLIDE TYPE 3: THANK YOU */}
                            {slide.layout === 'thank_you' && (
                                <div className="flex-1 relative z-10 flex flex-col items-center justify-center p-16 h-full text-center">
                                    <div className="relative z-10 flex flex-col items-center">
                                        <h1 className="text-8xl font-black text-white mb-8 drop-shadow-2xl tracking-tighter">Thank You</h1>
                                        <div className="w-48 h-2 bg-gradient-to-r from-[#df9b58] to-[#fcd3b6] rounded-full shadow-lg"></div>
                                        <p className="mt-8 text-[#fcd3b6] font-bold tracking-widest uppercase">Questions?</p>
                                    </div>
                                </div>
                            )}
                        </div>
                    </motion.div>
                ))}
            </div>
        </div>
    );
}
