import React, { useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
    Loader2, Download, Share2, Plus, Sparkles, Wand2, Layers,
    Presentation, Copy, Check, MessageCircle, Share
} from "lucide-react";
import pptxgen from "pptxgenjs";
import { useToast } from "@/components/ui/use-toast";
import { motion, AnimatePresence } from "framer-motion";

export function PPTGeneratorTab() {
    const { toast } = useToast();
    const [topic, setTopic] = useState('');
    const [grade, setGrade] = useState('');
    const [numSlides, setNumSlides] = useState('5'); // Default to 5 for better flow
    const [curriculum, setCurriculum] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedPPT, setGeneratedPPT] = useState<any>(null);
    const hasAutoGenerated = useRef(false);


    const handleGenerate = () => {
        if (!topic || !grade || !curriculum) {
            toast({
                title: "Missing Information",
                description: "Please fill in all required fields to generate the presentation.",
                variant: "destructive"
            });
            return;
        }

        setIsGenerating(true);
        setGeneratedPPT(null); // Clear previous

        // Simulate intelligent generation
        setTimeout(() => {
            const count = parseInt(numSlides);
            const newSlides = [];

            // 1. Curated, High-Reliability Image Collections (High-Res)
            const getImagesForTopic = (query: string): string[] => {
                const q = query.toLowerCase();

                // 1. Space / Science (High-Res NASA/Astro)
                if (q.includes('solar') || q.includes('space') || q.includes('planet') || q.includes('universe') || q.includes('astro')) {
                    return [
                        "https://images.unsplash.com/photo-1614730341194-75c60740a071?auto=format&fit=crop&w=1600&q=80",
                        "https://images.unsplash.com/photo-1614728853975-69c960c7229f?auto=format&fit=crop&w=1600&q=80",
                        "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
                        "https://images.unsplash.com/photo-1614313913007-2b4ae8ce32d6?auto=format&fit=crop&w=1600&q=80"
                    ];
                }

                // 2. Biology / Life Sciences
                if (q.includes('bio') || q.includes('cell') || q.includes('plant') || q.includes('animal') || q.includes('human') || q.includes('nature') || q.includes('body')) {
                    return [
                        "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=1600&q=80", // DNA
                        "https://images.unsplash.com/photo-1470058869958-2a77a61d123b?auto=format&fit=crop&w=1600&q=80", // Jungle
                        "https://images.unsplash.com/photo-1518152006812-edab29b069ac?auto=format&fit=crop&w=1600&q=80", // Lab
                        "https://images.unsplash.com/photo-1501147830916-ce44a6359892?auto=format&fit=crop&w=1600&q=80"  // Micro
                    ];
                }

                // 3. Math / Technology / Physics
                if (q.includes('math') || q.includes('algebra') || q.includes('geometry') || q.includes('physics') || q.includes('tech') || q.includes('code') || q.includes('robot')) {
                    return [
                        "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1600&q=80",
                        "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=1600&q=80",
                        "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1600&q=80",
                        "https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=1600&q=80"
                    ];
                }

                // 4. History / Social Studies / Culture
                if (q.includes('history') || q.includes('war') || q.includes('world') || q.includes('ancient') || q.includes('culture') || q.includes('monument')) {
                    return [
                        "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=1600&q=80",
                        "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=1600&q=80",
                        "https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&w=1600&q=80",
                        "https://images.unsplash.com/photo-1599930113854-d6d7fd521f10?auto=format&fit=crop&w=1600&q=80"
                    ];
                }

                // 5. Geography / Environment / Climate
                if (q.includes('geo') || q.includes('mount') || q.includes('ocean') || q.includes('weather') || q.includes('earth') || q.includes('environment')) {
                    return [
                        "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80", // Mountains
                        "https://images.unsplash.com/photo-1439405326854-014607f694d7?auto=format&fit=crop&w=1600&q=80", // Ocean
                        "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1600&q=80", // Forest
                        "https://images.unsplash.com/photo-1464802686167-b939a67e0621?auto=format&fit=crop&w=1600&q=80"  // Sky
                    ];
                }

                // 6. Literature / Language / Arts
                if (q.includes('lit') || q.includes('book') || q.includes('art') || q.includes('lang') || q.includes('write') || q.includes('philosophy')) {
                    return [
                        "https://images.unsplash.com/photo-1491841573634-28140fc7ced7?auto=format&fit=crop&w=1600&q=80", // Library
                        "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1600&q=80", // Abstract Art
                        "https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&w=1600&q=80", // Writing
                        "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1600&q=80"  // Books
                    ];
                }

                // Default / Generic Class (High-Res Education)
                return [
                    "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1600&q=80",
                    "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1600&q=80",
                    "https://images.unsplash.com/photo-1427504743055-e99aa31546d5?auto=format&fit=crop&w=1600&q=80",
                    "https://images.unsplash.com/photo-1577896238804-b9b870aa0412?auto=format&fit=crop&w=1600&q=80"
                ];
            };

            // 2. Intelligent Content Generator
            const getVariedContent = (phase: number, topic: string) => {
                const t = topic || "the subect";
                const q = topic.toLowerCase();

                // Specific Content Logic for Solar System (Demo Purpose)
                if (q.includes('solar') || q.includes('space')) {
                    const solarContents = [
                        // Phase 1: Intro
                        [
                            "The Solar System formed 4.6 billion years ago from the gravitational collapse of a giant interstellar molecular cloud.",
                            "It consists of the Sun and everything bound to it by gravity, including eight planets, dozens of moons, and millions of asteroids.",
                            "Understanding our cosmic neighborhood provides crucial insights into the formation of habitable worlds."
                        ],
                        // Phase 2: Inner Planets
                        [
                            "The four inner planets—Mercury, Venus, Earth, and Mars—are terrestrial, primarily composed of rock and metal.",
                            "Earth is the only known planet to harbor life, supported by its protective atmosphere and liquid water.",
                            "Mars shows evidence of past water activity, making it a prime candidate for future human exploration."
                        ],
                        // Phase 3: Outer Planets
                        [
                            "The four outer planets are gas giants, substantially more massive than the terrestrials.",
                            "Jupiter and Saturn are composed mainly of hydrogen and helium, while Uranus and Neptune are ice giants.",
                            "These planets possess extensive moon systems and planetary rings, offering diverse environments for study."
                        ],
                        // Phase 4: Exploration
                        [
                            "Humanity has sent robotic probes to every planet in the solar system, revealing dynamic landscapes.",
                            "The Voyager missions have extended beyond the heliopause, carrying messages from Earth to the stars.",
                            "Current missions focus on finding signs of ancient microbial life on Mars and icy moons."
                        ],
                        // Phase 5: Future
                        [
                            "Future colonization of the Moon and Mars is becoming a tangible goal for space agencies worldwide.",
                            "Asteroid mining could provide rare resources necessary for sustained deep-space travel.",
                            "The study of exoplanets continues to recontextualize our understanding of the Solar System's uniqueness."
                        ]
                    ];
                    return solarContents[(phase - 1) % solarContents.length];
                }

                // Content Templates based on "Flow" of presentation
                const contents = [
                    // Phase 1: Context / Introduction
                    [
                        `Establishing the core definitions of ${t} allows for a clearer understanding of its broader ecosystem.`,
                        `Historical context reveals how ${t} has evolved to become a critical component of modern systems.`,
                        `Key fundamental principles serve as the building blocks for more complex applications of ${t}.`
                    ],
                    // Phase 2: Mechanism / How it works
                    [
                        `Analyzing the internal mechanisms of ${t} highlights the intricate dependencies between its parts.`,
                        `Structural integrity is maintained through specific protocols unique to ${t}'s architecture.`,
                        `Process flows demonstrate the efficiency and systematic nature of ${t} in operation.`
                    ],
                    // Phase 3: Analysis / Data
                    [
                        `Quantitative data suggests a strong correlation between ${t} adoption and improved performance metrics.`,
                        `Critical analysis of recent studies validates the theoretical models proposed for ${t}.`,
                        `Evidence-based findings challenge traditional assumptions regarding the limitations of ${t}.`
                    ],
                    // Phase 4: Application / Real World
                    [
                        `Real-world case studies demonstrate the practical versatility of ${t} across various industries.`,
                        `Implementation strategies differ significantly based on the specific environmental constraints of ${t}.`,
                        `Scalability tests prove that ${t} can adapt to growing demands without losing efficiency.`
                    ],
                    // Phase 5: Future / Conclusion
                    [
                        `Emerging trends indicate that ${t} will play a pivotal role in next-generation developments.`,
                        `Future iterations are expected to address current limitations, expanding the scope of ${t}.`,
                        `Strategic integration of ${t} into new fields offers promising opportunities for innovation.`
                    ]
                ];

                // Modulo to cycle through content types if we have many slides
                const contentSet = contents[(phase - 1) % contents.length];
                return contentSet;
            };

            const sessionImages = getImagesForTopic(topic);
            const formatTitle = (str: string) => str.split(' ').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
            const displayTitle = formatTitle(topic);

            // Slide 1: Title
            newSlides.push({
                title: displayTitle,
                subtitle_1: `GRADE ${grade} • ${curriculum.toUpperCase()}`,
                subtitle_2: "Presented by Co-Teacher AI",
                layout: "organic_title",
                image: sessionImages[0],
                theme: "custom_teal"
            });

            // Middle Slides (Timeline Process)
            for (let i = 1; i < count - 1; i++) {
                const imgIndex = 1 + ((i - 1) % (sessionImages.length - 1));
                const slideContent = getVariedContent(i, displayTitle);

                // Theme rotation for visual variety
                const themes = ['blue', 'orange', 'purple', 'emerald', 'rose'];
                const currentTheme = themes[(i - 1) % themes.length];

                // Titles variations
                const titles = [
                    `Introduction to ${displayTitle}`,
                    `Core Mechanisms`,
                    `Critical Analysis`,
                    `Real-World Applications`,
                    `Future Implications`,
                    `Summary of findings`
                ];
                const slideTitle = titles[(i - 1) % titles.length] || `Phase ${i} Insights`;

                newSlides.push({
                    title: slideTitle,
                    content: slideContent,
                    layout: "timeline_process",
                    image: sessionImages[imgIndex % sessionImages.length],
                    theme: currentTheme,
                    tag: ["Context", "Mechanism", "Data", "Application", "Future"][(i - 1) % 5]
                });
            }

            // Last Slide: Thank You
            if (count > 1) {
                newSlides.push({
                    title: "Thank You",
                    layout: "thank_you",
                    image: sessionImages[sessionImages.length - 1]
                });
            }

            setGeneratedPPT({
                title: `${topic} (${curriculum.toUpperCase()} - Grade ${grade})`,
                slides: newSlides
            });
            setIsGenerating(false);
        }, 2000);
    };

    useEffect(() => {
        const params = new URLSearchParams(window.location.search);
        const urlTopic = params.get('topic');
        const urlGrade = params.get('grade');
        const urlCurriculum = params.get('curriculum');
        const auto = params.get('autoGenerate');

        if (urlTopic) setTopic(urlTopic);
        if (urlGrade) setGrade(urlGrade);
        if (urlCurriculum) setCurriculum(urlCurriculum);

        if (auto === 'true' && urlTopic && urlGrade && urlCurriculum && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            // Delay slightly to ensure states are set
            setTimeout(() => {
                handleGenerate();
            }, 500);
        }
    }, []);

    const handleDownloadPPTX = () => {
        if (!generatedPPT) return;

        try {
            const pres = new pptxgen();
            pres.title = generatedPPT.title;

            generatedPPT.slides.forEach((slide: any) => {
                const pptSlide = pres.addSlide();

                // Background
                if (slide.image) {
                    pptSlide.background = { path: slide.image };
                } else if (slide.layout === 'organic_title' || slide.layout === 'thank_you') {
                    pptSlide.background = { color: '409c95' };
                } else {
                    pptSlide.background = { color: 'f8fafc' };
                }

                // Add Title
                pptSlide.addText(slide.title, {
                    x: 0.5,
                    y: 0.5,
                    w: '90%',
                    h: 1,
                    fontSize: 44,
                    bold: true,
                    color: slide.layout === 'timeline_process' ? 'FFFFFF' : 'FFFFFF',
                    align: 'center',
                    valign: 'middle',
                    inset: 1
                });

                // Add Content/Body
                if (slide.content && Array.isArray(slide.content)) {
                    const bodyText = slide.content.map((point: string, i: number) => `${i + 1}. ${point}`).join('\n\n');
                    pptSlide.addText(bodyText, {
                        x: 0.7,
                        y: 1.8,
                        w: '80%',
                        h: 3,
                        fontSize: 18,
                        color: 'FFFFFF',
                        valign: 'top',
                        bullet: true
                    });
                }

                if (slide.subtitle_1) {
                    pptSlide.addText(slide.subtitle_1, {
                        x: 0.5,
                        y: 3.5,
                        w: '90%',
                        fontSize: 24,
                        color: 'fcd3b6',
                        align: 'center',
                        bold: true
                    });
                }

                if (slide.subtitle_2) {
                    pptSlide.addText(slide.subtitle_2, {
                        x: 0.5,
                        y: 4.2,
                        w: '90%',
                        fontSize: 16,
                        color: 'ecfdf5',
                        align: 'center'
                    });
                }
            });

            pres.writeFile({ fileName: `${generatedPPT.title.replace(/\s+/g, '_')}.pptx` });
            toast({
                title: "Download Started",
                description: "Your presentation is being downloaded.",
            });
        } catch (error) {
            console.error("PPT Generation Error:", error);
            toast({
                title: "Download Failed",
                description: "Failed to generate PowerPoint file.",
                variant: "destructive"
            });
        }
    };

    const handleShare = async () => {
        if (!generatedPPT) return;

        const baseUrl = window.location.origin + window.location.pathname;
        const shareUrl = `${baseUrl}?tab=ppt&topic=${encodeURIComponent(topic)}&grade=${encodeURIComponent(grade)}&curriculum=${encodeURIComponent(curriculum)}&autoGenerate=true`;

        const shareData = {
            title: `Check out this PPT on ${topic}`,
            text: `I generated a professional presentation on "${topic}" using Co-Teacher AI. Take a look!`,
            url: shareUrl
        };

        // 1. Try Native Share if on mobile
        if (navigator.share && /Android|iPhone|iPad/i.test(navigator.userAgent)) {
            try {
                await navigator.share(shareData);
                toast({ title: "Shared successfully!" });
                return;
            } catch (err) {
                console.log("Native share failed or cancelled");
            }
        }

        // 2. Fallback: Copy Link
        navigator.clipboard.writeText(shareUrl);

        // 3. Open WhatsApp for Desktop/Web
        const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(shareData.text + " " + shareUrl)}`;
        window.open(whatsappUrl, '_blank');

        toast({
            title: "Link Copied & WhatsApp Opened",
            description: "Share link is ready in your clipboard and WhatsApp.",
        });
    };

    return (
        <div className="space-y-6 max-w-6xl mx-auto pb-20">
            {/* Header / Input Config Section */}
            <div className="flex flex-col md:flex-row gap-6 items-start">
                <Card className="flex-1 bg-gradient-to-br from-indigo-50 to-white border-indigo-100 shadow-md">
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2 text-indigo-700">
                            <Sparkles className="w-5 h-5" />
                            AI Presentation Generator
                        </CardTitle>
                        <CardDescription>
                            Create professional, curriculum-aligned presentations in seconds.
                        </CardDescription>
                    </CardHeader>
                    <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="space-y-2">
                            <Label>Topic</Label>
                            <Input
                                placeholder="e.g. Solar System, Photosynthesis, WW2"
                                value={topic}
                                onChange={(e) => setTopic(e.target.value)}
                                className="border-indigo-200 focus:ring-indigo-500 bg-white/50"
                            />
                        </div>
                        <div className="space-y-2">
                            <Label>Curriculum</Label>
                            <Select value={curriculum} onValueChange={setCurriculum}>
                                <SelectTrigger className="border-indigo-200 bg-white/50">
                                    <SelectValue placeholder="Select Curriculum" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="CBSE">CBSE</SelectItem>
                                    <SelectItem value="ICSE">ICSE</SelectItem>
                                    <SelectItem value="SSC">SSC</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                        <div className="space-y-2">
                            <Label>Grade Level</Label>
                            <Select value={grade} onValueChange={setGrade}>
                                <SelectTrigger className="border-indigo-200 bg-white/50">
                                    <SelectValue placeholder="Select Class" />
                                </SelectTrigger>
                                <SelectContent>
                                    {Array.from({ length: 12 }, (_, i) => (i + 1).toString()).map(g => (
                                        <SelectItem key={g} value={g}>Grade {g}</SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                        <div className="space-y-2">
                            <Label>Number of Slides</Label>
                            <Select value={numSlides} onValueChange={setNumSlides}>
                                <SelectTrigger className="border-indigo-200 bg-white/50">
                                    <SelectValue placeholder="5 Slides" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="3">3 Slides (Short)</SelectItem>
                                    <SelectItem value="5">5 Slides (Standard)</SelectItem>
                                    <SelectItem value="8">8 Slides (Detailed)</SelectItem>
                                    <SelectItem value="10">10 Slides (Comprehensive)</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                    </CardContent>
                </Card>

                <div className="w-full md:w-64 flex flex-col gap-3">
                    <Button
                        size="lg"
                        className="w-full h-16 text-lg bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-700 hover:to-violet-700 shadow-xl transition-all hover:scale-105"
                        onClick={handleGenerate}
                        disabled={isGenerating}
                    >
                        {isGenerating ? (
                            <>
                                <Loader2 className="mr-2 h-5 w-5 animate-spin" /> Generating...
                            </>
                        ) : (
                            <>
                                <Wand2 className="mr-2 h-5 w-5" /> Generate PPT
                            </>
                        )}
                    </Button>
                    <div className="bg-indigo-900/5 p-4 rounded-xl border border-indigo-100 text-xs text-indigo-700 space-y-2">
                        <div className="flex items-center gap-2 font-semibold">
                            <Layers className="w-4 h-4" /> Pro Features Active
                        </div>
                        <ul className="list-disc list-inside space-y-1 opacity-80">
                            <li>HD Unsplash Images</li>
                            <li>Smart Layout Engine</li>
                            <li>Auto-Theming</li>
                        </ul>
                    </div>
                </div>
            </div>

            {/* PREVIEW AREA */}
            <AnimatePresence>
                {generatedPPT && (
                    <motion.div
                        initial={{ opacity: 0, y: 40 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0 }}
                        className="space-y-8"
                    >
                        <div className="flex items-center justify-between border-b pb-4">
                            <div>
                                <h2 className="text-2xl font-bold text-slate-900">Generated Presentation</h2>
                                <p className="text-slate-500 text-sm mt-1">{generatedPPT.title}</p>
                            </div>
                            <div className="flex gap-2">
                                <Button
                                    onClick={handleDownloadPPTX}
                                    className="bg-[#4F46E5] hover:bg-[#4338ca] text-white gap-2 shadow-sm"
                                >
                                    <Download className="w-4 h-4" /> Download .PPTX
                                </Button>
                                <Button
                                    variant="outline"
                                    onClick={handleShare}
                                    className="gap-2"
                                >
                                    <Share2 className="w-4 h-4" /> Share
                                </Button>
                            </div>
                        </div>

                        <div className="flex flex-col gap-12 max-w-4xl mx-auto">
                            {generatedPPT.slides.map((slide: any, idx: number) => (
                                <motion.div
                                    key={idx}
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: idx * 0.1 }}
                                    className="relative group perspective-1000"
                                >
                                    <div className="absolute -top-3 left-0 bg-slate-900 text-white text-xs font-bold px-3 py-1 rounded-t-lg z-10">
                                        Slide {idx + 1}
                                    </div>

                                    {/* Slide Container */}
                                    <div className="bg-black border-4 border-slate-900 rounded-xl overflow-hidden aspect-video shadow-2xl flex flex-col relative text-white">

                                        {/* Common Background: Clean Professional Look */}
                                        <div className="absolute inset-0 z-0 overflow-hidden">
                                            {/* Solid Professional Teal for Title & Thank You */}
                                            {(slide.layout === 'organic_title' || slide.layout === 'thank_you') && (
                                                <div className="absolute inset-0 bg-[#409c95]"></div>
                                            )}

                                            {/* Clean Background for Timeline/Process */}
                                            {slide.layout === 'timeline_process' && (
                                                <div className="absolute inset-0">
                                                    <img src={slide.image} alt="Background" className="w-full h-full object-cover transform scale-110 transition-transform duration-[10000ms] ease-out" />
                                                    {/* Lighter overlay to show image more clearly */}
                                                    <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-[1px]"></div>
                                                </div>
                                            )}
                                        </div>

                                        {/* SLIDE TYPE 1: PROFESSIONAL TITLE SLIDE (Text Only) */}
                                        {slide.layout === 'organic_title' && (
                                            <div className="flex-1 relative z-10 flex flex-col items-center justify-center p-16 h-full text-center">
                                                <div className="max-w-4xl">
                                                    <h1 className="text-7xl font-black text-white leading-tight mb-8 drop-shadow-lg tracking-tight">
                                                        {slide.title}
                                                    </h1>
                                                    <div className="w-48 bg-[#df9b58] h-2 mb-10 mx-auto rounded-full shadow-lg"></div>
                                                    <p className="text-3xl text-[#fcd3b6] font-bold mb-4 tracking-wide uppercase drop-shadow-md">{slide.subtitle_1 || 'Grade 10 • CBSE'}</p>
                                                    <p className="text-xl text-emerald-50 font-medium tracking-widest uppercase">{slide.subtitle_2 || 'Presented by Co-Teacher AI'}</p>
                                                </div>
                                            </div>
                                        )}

                                        {/* SLIDE TYPE 2: TIMELINE / PROCESS SLIDE (Themed Professional) */}
                                        {slide.layout === 'timeline_process' && (
                                            <div className="flex-1 relative z-10 flex items-center justify-center h-full">

                                                {/* VARIATION 1: Split Layout (Text Left / Image Right) - For Visual Interest */}
                                                {idx % 2 !== 0 ? (
                                                    <div className="flex w-full h-full">
                                                        {/* Text Side (60%) */}
                                                        <div className="w-[60%] p-12 flex flex-col justify-center space-y-8 bg-white z-20 shadow-2xl">
                                                            <div className="mb-2">
                                                                {slide.tag && (
                                                                    <span className={`inline-block px-4 py-1 rounded-full text-xs font-bold uppercase tracking-widest mb-4 text-white
                                                                        ${slide.theme === 'blue' ? 'bg-blue-500' :
                                                                            slide.theme === 'orange' ? 'bg-orange-500' :
                                                                                slide.theme === 'purple' ? 'bg-purple-500' :
                                                                                    slide.theme === 'emerald' ? 'bg-emerald-500' :
                                                                                        slide.theme === 'rose' ? 'bg-rose-500' : 'bg-[#345d67]'}`}>
                                                                        {slide.tag}
                                                                    </span>
                                                                )}
                                                                <h3 className={`text-5xl font-black tracking-tight leading-tight
                                                                    ${slide.theme === 'blue' ? 'text-blue-900' :
                                                                        slide.theme === 'orange' ? 'text-orange-900' :
                                                                            slide.theme === 'purple' ? 'text-purple-900' :
                                                                                slide.theme === 'emerald' ? 'text-emerald-900' :
                                                                                    slide.theme === 'rose' ? 'text-rose-900' : 'text-[#345d67]'}`}>
                                                                    {slide.title}
                                                                </h3>
                                                            </div>

                                                            <div className="space-y-6">
                                                                {slide.content.slice(0, 2).map((point: string, i: number) => (
                                                                    <div key={i} className="flex gap-4">
                                                                        <div className={`w-12 h-12 shrink-0 rounded-xl flex items-center justify-center text-white font-bold text-lg shadow-md mt-1
                                                                            ${slide.theme === 'blue' ? 'bg-blue-600' :
                                                                                slide.theme === 'orange' ? 'bg-orange-600' :
                                                                                    slide.theme === 'purple' ? 'bg-purple-600' :
                                                                                        slide.theme === 'emerald' ? 'bg-emerald-600' :
                                                                                            slide.theme === 'rose' ? 'bg-rose-600' : 'bg-[#345d67]'}`}>
                                                                            0{i + 1}
                                                                        </div>
                                                                        <p className="text-slate-600 text-lg font-medium leading-relaxed">{point}</p>
                                                                    </div>
                                                                ))}
                                                            </div>
                                                        </div>

                                                        {/* Image Side (40%) */}
                                                        <div className="w-[40%] relative overflow-hidden">
                                                            <div className={`absolute inset-0 opacity-20 bg-black`}></div>
                                                            <img
                                                                src={slide.image}
                                                                alt="Slide Visual"
                                                                className="w-full h-full object-cover transform hover:scale-105 transition-transform duration-1000"
                                                            />
                                                            {/* Overlay Gradient */}
                                                            <div className={`absolute inset-0 bg-gradient-to-r from-white via-transparent to-transparent opacity-100`}></div>
                                                        </div>
                                                    </div>
                                                ) : (
                                                    /* VARIATION 2: Centered Layout (Pro Visual Version) */
                                                    <div className="w-full max-w-5xl flex flex-col justify-center gap-10 p-16 relative z-10">

                                                        {/* Large Centered Visual Card */}
                                                        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-[80%] opacity-10 bg-white/5 rounded-3xl -z-10 border border-white/10 blur-xl"></div>

                                                        {/* Header Section with Tag */}
                                                        <div className="text-center mb-8">
                                                            {slide.tag && (
                                                                <span className={`inline-block px-5 py-1.5 rounded-full text-xs font-black uppercase tracking-widest mb-6 text-white shadow-lg
                                                                    ${slide.theme === 'blue' ? 'bg-blue-500 shadow-blue-500/20' :
                                                                        slide.theme === 'orange' ? 'bg-orange-500 shadow-orange-500/20' :
                                                                            slide.theme === 'purple' ? 'bg-purple-500 shadow-purple-500/20' :
                                                                                slide.theme === 'emerald' ? 'bg-emerald-500 shadow-emerald-500/20' :
                                                                                    slide.theme === 'rose' ? 'bg-rose-500 shadow-rose-500/20' : 'bg-[#345d67]'}`}>
                                                                    {slide.tag}
                                                                </span>
                                                            )}
                                                            <h3 className="text-6xl font-black mb-4 tracking-tight text-white drop-shadow-2xl">
                                                                {slide.title}
                                                            </h3>
                                                            <div className="flex justify-center flex-wrap gap-4 mt-8">
                                                                {slide.content.slice(0, 3).map((point: string, i: number) => (
                                                                    <div key={i} className="flex-1 min-w-[300px] bg-white/10 backdrop-blur-md p-8 rounded-3xl border border-white/20 shadow-2xl hover:bg-white/15 transition-all group overflow-hidden relative">
                                                                        <div className="absolute -top-4 -right-4 w-16 h-16 bg-white/5 rounded-full blur-xl group-hover:bg-white/10 transition-all"></div>
                                                                        <div className={`w-12 h-12 rounded-xl flex items-center justify-center text-white font-black text-xl mb-6 shadow-lg
                                                                            ${slide.theme === 'blue' ? 'bg-blue-600' :
                                                                                slide.theme === 'orange' ? 'bg-orange-600' :
                                                                                    slide.theme === 'purple' ? 'bg-purple-600' :
                                                                                        slide.theme === 'emerald' ? 'bg-emerald-600' :
                                                                                            slide.theme === 'rose' ? 'bg-rose-600' : 'bg-[#345d67]'}`}>
                                                                            0{i + 1}
                                                                        </div>
                                                                        <p className="text-indigo-50 text-xl font-bold leading-relaxed">{point}</p>
                                                                    </div>
                                                                ))}
                                                            </div>
                                                        </div>
                                                    </div>
                                                )}
                                            </div>
                                        )}

                                        {/* SLIDE TYPE 3: THANK YOU / CONTACT (Topnotch Pro Version) */}
                                        {slide.layout === 'thank_you' && (
                                            <div className="flex-1 relative z-10 flex flex-col items-center justify-center p-16 h-full text-center overflow-hidden">

                                                {/* Background Image Overlay */}
                                                <div className="absolute inset-0 opacity-20">
                                                    <img
                                                        src={slide.image}
                                                        alt="Background"
                                                        className="w-full h-full object-cover blur-sm transform scale-105"
                                                    />
                                                    <div className="absolute inset-0 bg-[#345d67]/90 mix-blend-multiply"></div>
                                                </div>

                                                <div className="relative z-10 flex flex-col items-center">
                                                    <h1 className="text-9xl font-black text-white mb-8 drop-shadow-2xl tracking-tighter">Thank You</h1>
                                                    <div className="w-48 h-2 bg-gradient-to-r from-[#df9b58] to-[#fcd3b6] rounded-full shadow-lg opacity-90"></div>
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                </motion.div>
                            ))}
                            <Button variant="ghost" className="border-2 border-dashed border-slate-300 h-24 hover:bg-slate-50 hover:border-indigo-300 text-slate-500 font-bold rounded-xl">
                                <Plus className="w-6 h-6 mr-2" /> Add New Slide
                            </Button>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}
